[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
dependsOn = ['setup']
cmds = [
  'python -m pip install streamlit==1.46.1 --break-system-packages',
  'python -m pip install pandas==2.3.1 --break-system-packages',
  'python -m pip install paramiko==3.5.1 --break-system-packages',
  'python -m pip install schedule==1.2.2 --break-system-packages',
  'python -m pip install requests==2.31.0 --break-system-packages'
]

[start]
cmd = 'python railway_app.py'